### ISSUE TITLE
OrderStatusEnum has no CANCELLED value

### ISSUE THREAD

**Issue by NathanSmeltzer** [goshippo/shippo-python-sdk#49]
Retrieving a cancelled order returns the error:
ValueError: 'CANCELLED' is not a valid OrderStatusEnum

This seems due to [OrderStatusEnum](https://github.com/goshippo/shippo-python-sdk/blob/main/src/shippo/models/components/orderstatusenum.py) not having a CANCELLED value, which is an order status according to the [docs](https://docs.goshippo.com/docs/orders/orders/#order-status-values-order_status-field).

The code
```
s = shippo.Shippo(api_key_header=config("SHIPPO_API_KEY"))
s.orders.list(page=1, results=50)
```

**Comment by shippo-lueders** [comment]
Thanks for raising the issue, I've submitted a fix for our spec which should get merged tomorrow

**Comment by shippo-lueders** [comment]
Fixed by https://github.com/goshippo/shippo-python-sdk/pull/51
